### ISSUE TITLE
Forgot Password Breaks Autocomplete Saved Passwords

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#679]
No e-mail arrived.

On a side-note, I get emails to my spam folder using mail.com.

**Comment by bigbass1997** [comment]
Email arrived for me in inbox. Using a gmail.com account.

**Comment by meshuggahtas** [comment]
Today I did get the email in mail.com inbox, email confirmation still comes to spam folder. 
gmail.com OK, both e-mail came to inbox.

Yesterday I tried to reset password 3 times but no email came.

Is there a maximum limit of emails to send per users? Or can we somehow check that I did pressed reset password 3 times.

**Comment by meshuggahtas** [comment]
Retested with gmail.com and mail.com, both of them came in and could reset my password.

The issue is solved, but there is another relevant problem: **your browser won't know what is your username, so it will be saved to the email address** (the lost password link forwards you to 3 fields: email, password, password but you login with your username).

**Comment by TiKevin83** [comment]
need to disable autocomplete on the email input and add a hidden username input with the username prefilled, that should fix autocomplete updates.

**Comment by TiKevin83** [comment]
retested on staging, still broken in the forgot password flow as the user is not seen as logged in on the forgot password page for the user name to be stored in the hidden field

**Comment by adelikat** [comment]
I'm not sure what you want to be done here.  The forgot password is never going to be used by a logged in user, that's the reason they need to use it.  So I do not see the point of attempting to store a username.

**Comment by TiKevin83** [comment]
I need to research how other sites handle it still

**Comment by adelikat** [comment]
Any updates on this?

**Comment by adelikat** [comment]
I'm going to bump this out of a priority milestone.  I'm not sure what makes it urgent and I'm not seeing any forward progress on it.
